### ISSUE TITLE
Add api-key on all calls

### ISSUE THREAD

**Issue by JorisDebonnet** [ahmadawais/Sendy-PHP-API#7]
See https://sendy.co/get-updated: Starting with version 4.0.3.3, Sendy requires the `api_key` on the `subscribe` endpoint. 

Anticipating future API changes, I suggest just adding the api_key on all calls (in the general `query` method), as this this should simplify some of the code, and it should be backwards compatible since it will just be ignored on versions that don't need it.

**Comment by BitpopCoin** [comment]
Yes this is critical

**Comment by ahmadawais** [comment]
Is it backward compatible? I'll happily accept a PR for this.

**Comment by BitpopCoin** [comment]
#8

**Comment by JorisDebonnet** [comment]
> Here's the PR #8

@BitpopCoin, great, looks good to fix the subscribe endpoint at least! 

I would have suggested however to fix this in the general `query` method, because then you can remove the api_key from all specific methods (subscribe, unsubscribe, delete, campaign, subCount, ...). It doesn't really makes a difference functionality, I admit, but I just think that would be the most clean solution 😄

**Comment by BitpopCoin** [comment]
You're right. I did see

Global options for return.

Which threw me off since it says return but that's very wrong. It's the post. I think that part came from the older library.

**Comment by BitpopCoin** [comment]
> > Here's the PR #8
> 
> @BitpopCoin, great, looks good to fix the subscribe endpoint at least!
> 
> I would have suggested however to fix this in the general `query` method, because then you can remove the api_key from all specific methods (subscribe, unsubscribe, delete, campaign, subCount, ...). It doesn't really makes a difference functionality, I admit, but I just think that would be the most clean solution

Ok I added it to the global. Can you test it? #8

**Comment by JorisDebonnet** [comment]
> 
> 
> Is it backward compatible? I'll happily accept a PR for this.

It's backwards compatible indeed! And I tested it, see #7.

**Comment by Fossil01** [comment]
I'm having the same issue.  Error: `API key not passed`

**Comment by BitpopCoin** [comment]
> I'm having the same issue. Error: `API key not passed`

Use this https://raw.githubusercontent.com/ahmadawais/Sendy-PHP-API/0cb107b6986b71487160ede72dc1bedd20f3f1cf/src/Sendy.php

**Comment by harsha-mohan** [comment]
Hi there! Does anyone know when will this change be merged into master?

**Comment by ahmadawais** [comment]
I need to test it and unable to find the time. As soon as I do, I'll merge it. Hopefully this week.

**Comment by harsha-mohan** [comment]
Hi @ahmadawais 

So I was able to contact Sendy and they can help you out. Just explain why are you testing this and maybe they can offer you a temporary free license. Send an email to hello@sendy.co 

Follow up on my conversation on twitter [https://twitter.com/iamharshamohan/status/1219987558236590081](url)

Hope this helps

Thank you
Harsha

**Comment by Fossil01** [comment]
@ahmadawais I have donated that amount 2 weeks ago.

**Comment by ahmadawais** [comment]
Hey, @Fossil01!
Thanks for letting me know and for helping me upgrade. Appreciate that. I just check that, somehow missed the notification. Going to test and merge a working PR now. Peace! ✌️

**Comment by BitpopCoin** [comment]
I think you forgot to set these to 1


			// Comment to disable this SSL peer verification for testing.
			curl_setopt( $ch, CURLOPT_SSL_VERIFYPEER, 0 );
			// Comment to disable this SSL host verification for testing.
			curl_setopt( $ch, CURLOPT_SSL_VERIFYHOST, 0 );

**Comment by ahmadawais** [comment]
Fixed in the latest v4 release.
