### ISSUE TITLE
Now api key is required

### ISSUE THREAD

**Issue by fernandoch777** [ahmadawais/Sendy-PHP-API#9]
Hello, now the api key is required for every call, is this ready for that change?

**Comment by ahmadawais** [comment]
YES! You should update to the latest and read the changelog instead of creating extra workload for me by creating issues that are already solved. I don't get paid to manage this project, please be kind and empathatic towards others who have to spend time on FOSS (Free & Open Source Software).

**Comment by fernandoch777** [comment]
Sorry for that, but I am not a dev and I checked your subscribe example and there is no api_key in there so this is why I asked.
And sorry again for the super extra work I gave you.

**Comment by ahmadawais** [comment]
Actually, once you give this Wrapper the API (when you instantiate it in
step #1) the API call for every other call is taken care of it for all your
requests. Just use the latest version.

Also, this project is supposed to use by developers.

>
